### ISSUE TITLE
DaemonSet is running with default Service Account

### ISSUE THREAD

**Issue by czunker** [mondoohq/mondoo-operator#132]
**Describe the bug**

The mondoo-client created by the DaemonSet is runnig with the default ServiceAccount of the namespace.

The mondoo-client created by the Deployment is running with its own ServiceAccount `mondoo-operator-workload`.

**To Reproduce**
1. Install mondoo-operator version 0.0.9 (I used the kubectl docs)
2. Wait for DaemonSet to be installed
3. Execute `kubectl get daemonset.apps/mondoo-client -o yaml | grep Account`
This will not return any result.

**Expected behavior**
I would expect the DaemonSet to also use the ServiceAccount `mondoo-operator-workload` or another ServiceAccount, but not the default ServiceAccount.

**Kubernetes:**
 - OS: Ubuntu 20.04
 - Version mondoo-operator 0.0.9
 - Kubernetes version: 1.22.5

**Comment by chris-rock** [comment]
Thank you @czunker for reporting. I 100% agree that we should add a custom service account.

**Comment by czunker** [comment]
Can you please re-open this issue?

With operator version 0.2.5 the DaemonSet is running with the default SA again. It seems, the dedicated SA was removed between 0.2.3 and 0.2.4.

I noticed it because our clusters are still running with Pod Security Policies enabled.
The default SA also triggers the `Pod should not run with default service account` policy of the `Kubernetes Application Benchmark`.

**Comment by imilchev** [comment]
> Can you please re-open this issue?
> 
> With operator version 0.2.5 the DaemonSet is running with the default SA again. It seems, the dedicated SA was removed between 0.2.3 and 0.2.4.
> 
> I noticed it because our clusters are still running with Pod Security Policies enabled. The default SA also triggers the `Pod should not run with default service account` policy of the `Kubernetes Application Benchmark`.

We did an audit on the RBAC rules that we apply for all workloads managed by the operator. The goal was to restrict the workloads to only have the minimum authorization to do their job. The background on the node scanning is that it does not need any access to the Kubernetes API, so we dropped the service account and we made sure it does not auto-mount the service account token for the default account (`automountServiceAccountToken: false`).

I believe the violation that you are observing is policy 5.1.5 from the CIS Kubernetes benchmark. This is the remediation stated in the document:

> Remediation:
Create explicit service accounts wherever a Kubernetes workload requires specific access
to the Kubernetes API server.
Modify the configuration of each default service account to include this value

Since we do not need Kubernetes API access it should be sufficient to just disable mounting the service account token, which we already do. I am interested in what is flagging the `DaemonSet` as an issue? Is this one of our policies or is it some other tool that is doing that?

**Comment by czunker** [comment]
Thanks, for re-opening this issue.

From the Kubernetes [docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server):

> if you do not specify a service account, it is automatically assigned the default service account in the same namespace

So in my understanding, no matter whether you use the API or not, the Pod gets a service account.
Perhaps, a valid approach is to create a service account without any RBAC assignment.

And that's the message seen in the Mondoo Web UI:
```
  {
    [failed] Pod "mondoo-operator" "mondoo-client-node-7gv8x" should disabled automount
    [failed] Pod "mondoo-operator" "mondoo-client-node-7gv8x" should not use deprecated service account
    [failed] Pod "mondoo-operator" "mondoo-client-node-7gv8x" should not use default service account
    podSpec[serviceAccountName] != null: true
  }
```

**Comment by imilchev** [comment]
Yes, that's what I pointed out. If no explicit service account is provided, then the default is used. What I am saying now is that probably our query for checking this specific part of the CIS benchmark should be updated. Using the default service account with `automountServiceAccountToken: false` should not trigger a violation (at least according to my interpretation of the CIS benchmark specification).

We will discuss this internally. We will either update the policy to not show violations in these cases or we will create a dedicated service account with no roles assigned to it for the node scanning. I will let you know once we have a conclusion on this matter

**Comment by czunker** [comment]
Thanks for the update.

**Comment by imilchev** [comment]
We just made a release and the error should disappear. I will close the issue for now. Please let us know if you still encounter any issues.
