### ISSUE TITLE
The Operator Namespace should be "mondoo-operator"

### ISSUE THREAD

**Issue by benr** [mondoohq/mondoo-operator#136]
The current namespace name of "mondoo-operator-system" is very technically accurate but unusual.  Consider other operator namespace names:

```
openebs                  Active   2y14d
cert-manager             Active   2y6d
klum                     Active   709d
argocd                   Active   687d
mondoo-operator-system   Active   2d7h
```

It would be more natural for the operator namespace to simply be "mondoo"

**Comment by chris-rock** [comment]
I like the idea @benr, @joelddiaz any thoughts?

**Comment by joelddiaz** [comment]
I agree that the 'mondoo-operator-system' name seems like a bit much.

This brings up an interesting discussion. In the operator/operand relationships I'm used to working with (OpenShift), you normally have the operator in a namespace following the convention SomeNamespace-operator, and the managed software running perhaps in the namespace SomeNamespace (sometimes the CRD for defining configuration allows specifying which namespace to place all the operand components into (especially if there can be more than one CRD instance of the operand to be managed)).

IIUC, for something like cert-manager and argocd, those are "native" k8s apps that have no existence outside of being scheduled on k8s. For something like the mondoo-client binary, this is something that can run outside of k8s, and the mondoo-operator is responsible for knowing how to effectively run it as a Pod on k8s (the more traditional operator/operand architecture).

In my mind, whether to run the operator and the operand in the same Namespace really comes down to whether we think it makes sense for there to be more than 1 MondooAuditConfig resource in a single cluster.

- If the answer is 'yes', then you likely want a 'targetNamespace' kind of field in MondooAuditConfig so that the mondoo-operator can manage multiple instances of the mondoo-client Pods.
- If the answer is 'no', then I believe we have the option of making the MondooAuditConfig CRD cluster-scoped and the MondooAuditConfig controller can enforce the idea of there being only one CRD (named 'mondoo-config' for example) for defining the single instance of the mondoo clients on that cluster. Whether to allow a targetNamespace field for the operand would have little consequence as there would only ever be one instance of the mondoo-client Pods.

Although being a "native" k8s app isn't enough to explain why there is or isn't an operator/operand relationship. I've also seen k8s-only apps that have an operator to simplify the configuration of a complex operand.

I hope that all made sense...

**Comment by joelddiaz** [comment]
I may have gotten lost in that wall of text I wrote as I wrote it. The point I wanted to make was that whether the namespace is called 'mondoo' vs 'mondoo-operator' really revolves around whether we think there will be more than one instance of the MondooAuditConfig CRD.

**Comment by chris-rock** [comment]
@joelddiaz and I discussed. We think the name should be `mondoo-operator`
