### ISSUE TITLE
Enforce the need for a ServiceAccount name when webhook enabled in non-default namespace

### ISSUE THREAD

**Issue by joelddiaz** [mondoohq/mondoo-operator#298]
The ScanAPI Deployment will need to make k8s API calls. While there is a ready-made ServiceAccount for precisely this purpose in the 'mondoo-operator' Namespace (for the Workload scanning), ~~we need to ensure (for now) that the .spec.Workloads.ServiceAccount field is filled out when setting up the ScanAPI Deployment in a Namespace that isn't 'mondoo-operator'.~~ , we need to ensure that the ServiceAccountName specified in .spec.Scanner.ServiceAccountName exists before creating the Depoyment.

This would be handled with something like:
```
if Mondoo.Namespace != "mondoo-operator" {
  exists := doesServiceAccountExists(Mondoo)
  if !exists {
    // log error
   // set condition
   return
  }
}
```

Criteria:
Write up some test case(s) to assert this behavior (should be failing if the tests are written first).

A functioning setup would mean that when a MondooAuditConfig in a non-default (ie non `mondoo-operator`) Namespace would log the error and return an overall error in the mondooauditconfig controller's Reconcile() loop and keep from starting up the ScanAPI Deployment/Pod.

**Comment by czunker** [comment]
Seems, this issue is no longer needed, because of the migration to `v1alpha2`.
The linked code snippet got removed during the update to `v1alpha2`: https://github.com/mondoohq/mondoo-operator/pull/305/files#diff-1786e239e5504de1031b83904f80438725cb4f2f2a5e9ca7a437f916091aeb39

The ServiceAccount for the workload scan has moved, has a default, and is now referenced this way: https://github.com/mondoohq/mondoo-operator/blob/main/controllers/workloads.go#L263

The ScanAPI references the same ServiceAccount the same way: https://github.com/mondoohq/mondoo-operator/blob/main/controllers/scanapi/resources.go#L126

The integration tests already include a test with a deployment to a custom namespace: https://github.com/mondoohq/mondoo-operator/blob/main/tests/integration/audit_config_namespace_test.go#L83

To  be on the save side, I tried the Helm install according to the [docs](https://github.com/mondoohq/mondoo-operator/blob/main/docs/user-manual.md) just with another namespace. Worked fine on my local Minikube cluster.

**Comment by czunker** [comment]
As it turned out, this change has security implications, because the operator would be able to read all Kubernetes Service Accounts. Think of it like reading `/etc/passwd` on Linux. With GKE Workload Identity or AWS IAM role association, this might even have more impact.

We will try another approach with #382
