### ISSUE TITLE
Investigate admission controller error behaviour

### ISSUE THREAD

**Issue by imilchev** [mondoohq/mondoo-operator#328]
A few times I encountered some errors in the admission controller that we deploy. I still don't know why but sometimes it was getting weird response from the scan API and then it fails. I only saw that by accident because in case an error like this happens, right now we just allow the resource. I understand that we probably implemented it like this so we are not intrusive in case our stuff doesn't work. However, I do see why this might turn out to be not an ideal solution. I think it might be better to just deny everything until the errors in the admission controller are resolved. If I have enabled the admission controller, I would expect it to do its work. In case it cannot because of misconfiguration or because of a bug my deployments should be blocked so at least I am aware of the issue. At that point I can decide whether I want to fix the problem or disable the admission controller.

**Comment by czunker** [comment]
Perhaps we can implement two options.

When the webhook is running in permissive mode, we could set the `failurePolicy` to `Ignore`. This way we do not block anything, no matter whether our webhook is working fine or not.

But when the webhook is running in enforcing mode, we should set the `failurePolicy` to `Fail`. Otherwise, it would be possible to disable/sabotage the webhook from inside the cluster and allow the creation of objects which would be denied otherwise.

In the enforcing case, one gets fast feedback to fix problems:
```
$ kubectl -n cz-test apply -f ../../ubuntu-priv.yaml
Error from server (InternalError): error when creating "../../ubuntu-priv.yaml": Internal error occurred: failed calling webhook "policy.k8s.mondoo.com": failed to call webhook: Post "https://mondoo-client-webhook-service.mondoo-operator.svc:443/validate-k8s-mondoo-com?timeout=10s": dial tcp 10.102.24.177:443: connect: connection refused
```

Perhaps it is possible to enhance status/error reporting in the case of permissive mode + `failurePolicy: Ignore`. When the operator detects these cases, it could update the `Status` of the `MondooAuditConfig`.

**Comment by czunker** [comment]
I reproduced the mentioned error behavior by scaling down the ScanAPI.

The webhook cannot talk to the ScanAPI, but the Pod creation is allowed. Perhaps we can also send a reply depending on the mode.
