### ISSUE TITLE
Run Cloud Tests on a regular schedule

### ISSUE THREAD

**Issue by czunker** [mondoohq/mondoo-operator#564]
**What is not working as you expected it?**
We have now cloud tests for EKS, AKS, and GKE. But we aren't using them.

**Where on the platform does it happen?**
GitHub Actions

**How do we replicate the issue?**
-

**Expected behavior (i.e. solution)**
We should run the tests on a regular schedule. The current agreed-on plan is to run them on a schedule every Sunday night.

**Other Comments**

**Comment by czunker** [comment]
How do we get notified about errors?

What about problems with the teardown of the Infrastructure? This can get costly.

**Comment by imilchev** [comment]
For the teardown we have set up alerts in the cloud account for GKE and AKS. They have a very low limit and will notify us if we are reaching it. Not sure how EKS is configured.

I don't think we can get notifications per email since this is a scheduled workflow. We can make a channel in discord for this and push the notifications there?

**Comment by czunker** [comment]
Discord sounds good to me. Perhaps we can re-use the discussed edge test channel for this also. So, making it the general purpose GitHub actions channel.

Will check on Budget alerts for EKS.

**Comment by czunker** [comment]
EKS is also covered.

**Comment by imilchev** [comment]
Discord notifications are configured. I will add the schedule for the cloud tests
